[tool.poetry]
name = "zhenxun_plugin_ddcheck"
version = "0.1.2"
description = " zhenxun 成分姬插件"
authors = ["polan <1114083149@qq.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"
httpx = ">=0.19.0"
Jinja2 = "^3.0.0"
